name: pipeline_session15

on:
  push:
    branches:
      - main

jobs :
  job1:
    runs-on: ubuntu-latest
    steps: 
      - run: mkdir folder1
      - name: list folders
        run: ls-al
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: list folders
        run: ls -al